export interface HttpStatus { code: number; name: string; desc: string }

export const HTTP_STATUS: HttpStatus[] = [
  { code: 100, name: 'Continue', desc: 'The server received the request headers; the client should send the body.' },
  { code: 101, name: 'Switching Protocols', desc: 'The server agrees to switch protocols as requested via the Upgrade header (e.g. to WebSocket).' },
  { code: 102, name: 'Processing', desc: 'WebDAV: the server has accepted the request but has not completed it yet.' },
  { code: 103, name: 'Early Hints', desc: 'Preliminary response used to send Link headers so the browser can preload resources.' },
  { code: 200, name: 'OK', desc: 'The request succeeded. The meaning depends on the method: GET returns the resource, POST returns the result.' },
  { code: 201, name: 'Created', desc: 'The request succeeded and a new resource was created, typically after POST or PUT.' },
  { code: 202, name: 'Accepted', desc: 'The request was accepted for processing but is not complete — common for async jobs.' },
  { code: 203, name: 'Non-Authoritative Information', desc: 'The response was modified by a proxy from the origin server’s 200 response.' },
  { code: 204, name: 'No Content', desc: 'Success with no body to return — typical for DELETE or a PUT that changed nothing visible.' },
  { code: 205, name: 'Reset Content', desc: 'Success; the client should reset the document view (e.g. clear a form).' },
  { code: 206, name: 'Partial Content', desc: 'The server is returning part of the resource in response to a Range header (video seeking, resumable downloads).' },
  { code: 207, name: 'Multi-Status', desc: 'WebDAV: the body contains multiple status codes for multiple resources.' },
  { code: 226, name: 'IM Used', desc: 'The server fulfilled a GET with instance manipulations applied (delta encoding).' },
  { code: 300, name: 'Multiple Choices', desc: 'The request has more than one possible response; the client should choose one.' },
  { code: 301, name: 'Moved Permanently', desc: 'The resource has a new permanent URL. Browsers and search engines update their references. May change POST to GET.' },
  { code: 302, name: 'Found', desc: 'Temporary redirect. The client should use the Location header for this request only. Historically changes POST to GET.' },
  { code: 303, name: 'See Other', desc: 'Redirect to another URL using GET — the standard way to redirect after a form POST.' },
  { code: 304, name: 'Not Modified', desc: 'The cached version is still valid (conditional GET with If-None-Match / If-Modified-Since). No body is sent.' },
  { code: 307, name: 'Temporary Redirect', desc: 'Like 302, but the method and body must not change — a POST stays a POST.' },
  { code: 308, name: 'Permanent Redirect', desc: 'Like 301, but the method and body must not change.' },
  { code: 400, name: 'Bad Request', desc: 'The server cannot process the request due to a client error — malformed syntax, invalid parameters, bad JSON.' },
  { code: 401, name: 'Unauthorized', desc: 'Authentication is required or has failed. Despite the name, it means "unauthenticated". Should include a WWW-Authenticate header.' },
  { code: 402, name: 'Payment Required', desc: 'Reserved for future use; some APIs use it for exhausted quotas or billing problems.' },
  { code: 403, name: 'Forbidden', desc: 'The client is authenticated but does not have permission. Re-authenticating will not help.' },
  { code: 404, name: 'Not Found', desc: 'The server cannot find the requested resource. Also used to hide the existence of a resource from unauthorised clients.' },
  { code: 405, name: 'Method Not Allowed', desc: 'The HTTP method is known but not supported for this resource (e.g. PUT on a read-only endpoint). Should include an Allow header.' },
  { code: 406, name: 'Not Acceptable', desc: 'The server cannot produce a response matching the Accept headers sent by the client.' },
  { code: 407, name: 'Proxy Authentication Required', desc: 'Like 401, but authentication must be done with the proxy.' },
  { code: 408, name: 'Request Timeout', desc: 'The server timed out waiting for the request. The client may retry.' },
  { code: 409, name: 'Conflict', desc: 'The request conflicts with the current state of the resource — e.g. an edit based on stale data, or a duplicate unique key.' },
  { code: 410, name: 'Gone', desc: 'The resource is permanently gone and no forwarding address is known. Search engines drop it faster than a 404.' },
  { code: 411, name: 'Length Required', desc: 'The server requires a Content-Length header.' },
  { code: 412, name: 'Precondition Failed', desc: 'A condition in If-Match / If-Unmodified-Since headers was not met — used for optimistic concurrency.' },
  { code: 413, name: 'Content Too Large', desc: 'The request body exceeds the server’s limit (formerly "Payload Too Large").' },
  { code: 414, name: 'URI Too Long', desc: 'The URL is longer than the server is willing to process — usually a GET with too much query data.' },
  { code: 415, name: 'Unsupported Media Type', desc: 'The request body format (Content-Type) is not supported by the server.' },
  { code: 416, name: 'Range Not Satisfiable', desc: 'The Range header asks for a portion outside the resource’s size.' },
  { code: 417, name: 'Expectation Failed', desc: 'The server cannot meet the Expect request header (usually Expect: 100-continue).' },
  { code: 418, name: "I'm a teapot", desc: 'April Fools joke from RFC 2324 (Hyper Text Coffee Pot Control Protocol). Some servers return it for blocked requests.' },
  { code: 421, name: 'Misdirected Request', desc: 'The request was sent to a server that cannot produce a response (wrong host on a shared TLS connection).' },
  { code: 422, name: 'Unprocessable Content', desc: 'The request is well-formed but semantically invalid — the standard code for validation errors in APIs.' },
  { code: 423, name: 'Locked', desc: 'WebDAV: the resource is locked.' },
  { code: 424, name: 'Failed Dependency', desc: 'WebDAV: the request failed because a previous request it depended on failed.' },
  { code: 425, name: 'Too Early', desc: 'The server refuses to process a request that might be replayed (TLS early data).' },
  { code: 426, name: 'Upgrade Required', desc: 'The client must switch to a different protocol, given in the Upgrade header.' },
  { code: 428, name: 'Precondition Required', desc: 'The server requires the request to be conditional (If-Match) to prevent lost updates.' },
  { code: 429, name: 'Too Many Requests', desc: 'Rate limit exceeded. Should include a Retry-After header telling the client when to try again.' },
  { code: 431, name: 'Request Header Fields Too Large', desc: 'Headers are too large — often a cookie that has grown out of control.' },
  { code: 451, name: 'Unavailable For Legal Reasons', desc: 'The resource is blocked for legal reasons (censorship, court order). Named after Fahrenheit 451.' },
  { code: 500, name: 'Internal Server Error', desc: 'A generic server-side failure — an unhandled exception, misconfiguration, or crash. Check the server logs.' },
  { code: 501, name: 'Not Implemented', desc: 'The server does not support the functionality required (usually an unknown HTTP method).' },
  { code: 502, name: 'Bad Gateway', desc: 'A proxy or load balancer received an invalid response from the upstream server — often the app behind it is down or crashed.' },
  { code: 503, name: 'Service Unavailable', desc: 'The server is temporarily overloaded or down for maintenance. Should include Retry-After.' },
  { code: 504, name: 'Gateway Timeout', desc: 'A proxy or load balancer did not get a response from the upstream server in time.' },
  { code: 505, name: 'HTTP Version Not Supported', desc: 'The server does not support the HTTP version used in the request.' },
  { code: 506, name: 'Variant Also Negotiates', desc: 'Server configuration error in content negotiation.' },
  { code: 507, name: 'Insufficient Storage', desc: 'WebDAV: the server cannot store the representation needed to complete the request.' },
  { code: 508, name: 'Loop Detected', desc: 'WebDAV: the server detected an infinite loop while processing the request.' },
  { code: 510, name: 'Not Extended', desc: 'Further extensions to the request are required for the server to fulfil it.' },
  { code: 511, name: 'Network Authentication Required', desc: 'The client must authenticate to gain network access — captive portals on public Wi-Fi.' },
];

export const CLASSES: Record<number, { name: string; blurb: string; tone: string }> = {
  1: { name: 'Informational', blurb: 'Request received, continuing process.', tone: 'bg-sky-100 text-sky-700 dark:bg-sky-500/15 dark:text-sky-300' },
  2: { name: 'Success', blurb: 'The action was received, understood and accepted.', tone: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300' },
  3: { name: 'Redirection', blurb: 'Further action is needed to complete the request.', tone: 'bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300' },
  4: { name: 'Client Error', blurb: 'The request contains bad syntax or cannot be fulfilled.', tone: 'bg-rose-100 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300' },
  5: { name: 'Server Error', blurb: 'The server failed to fulfil a valid request.', tone: 'bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300' },
};
